name: CI
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: GitHub Action for Yarn
      uses: Borales/actions-yarn@v2.3.0
      with:
        cmd: deploy
